sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera1/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: /camera1/filtered_cloud
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera2/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0
    filtered_cloud_topic: /camera2/filtered_cloud    
#  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
#    point_cloud_topic: depthcam2/points
#    max_range: 5.0
#    point_subsample: 1
#    padding_offset: 0.1
#    padding_scale: 1.0
#    max_update_rate: 1.0
#    filtered_cloud_topic: filtered_cloud2  
#  []
